# Generated by Django 2.2.13 on 2020-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockExchangeSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Símbolo')),
                ('name', models.CharField(max_length=200, verbose_name='Primeiro nome')),
            ],
        ),
    ]
