# Generated by Django 2.2.13 on 2020-06-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
        ('stonks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolApiHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_control.Pessoa')),
            ],
        ),
    ]
