# Generated by Django 2.2.13 on 2020-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0002_symbolapihistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySymbolInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=500, verbose_name='Information')),
                ('output_size', models.CharField(max_length=100, verbose_name='Output size')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('last_refreshed', models.DateField(verbose_name='Last Refreshed')),
            ],
        ),
        migrations.CreateModel(
            name='DailySymbolTimeSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
