# Generated by Django 2.2.13 on 2020-06-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0003_dailysymbolinformation_dailysymboltimeserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysymbolinformation',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonks.SymbolApiHistory'),
        ),
        migrations.AddField(
            model_name='dailysymboltimeserie',
            name='symbol_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonks.DailySymbolInformation'),
        ),
    ]
