# Generated by Django 2.2.13 on 2020-06-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0004_auto_20200628_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysymbolinformation',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stonks.StockExchangeSymbol'),
        ),
    ]
