# Generated by Django 2.2.13 on 2020-06-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0005_auto_20200628_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolapihistory',
            name='author',
        ),
    ]
