# Generated by Django 2.2.13 on 2020-06-28 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0007_userwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='symbol_information',
            new_name='owner',
        ),
    ]
