# Generated by Django 2.2.13 on 2020-06-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0009_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
