# Generated by Django 2.2 on 2020-06-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks', '0010_purchase_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysymbolinformation',
            name='last_refreshed',
            field=models.DateTimeField(verbose_name='Last Refreshed'),
        ),
    ]
